//autogenID_HBELI
BEGIN
		DECLARE URUT INT;
    DECLARE TGL VARCHAR(6);
    DECLARE NOTA VARCHAR(10);

    SET TGL = DATE_FORMAT(NOW(), '%d%m%y');
    SELECT IFNULL(COUNT(*),0)+1 INTO URUT
    FROM h_beli
    WHERE SUBSTR(no_nota,1,7) = CONCAT('N',TGL);

    SET NOTA = CONCAT('N',TGL,LPAD(URUT,3,'0'));
		RETURN NOTA;
END
